pointcloud_filter_node:
  ros__parameters:
    input_topic: "/points"
    output_topic: "/points/filtered"
    y_rotation_angle: 0.1570796 
    x_traslation: 0.
    y_traslation: 0.
    z_traslation: 1.
    gradient: true
    intensity: false
    angle_zones:
      - "start: 0.0, end: 0.084, downsample: 45"  #OT128
      - "start: 0.084, end: 0.558, downsample: 10"
      - "start: 0.558, end: 0.879, downsample: 1"
      - "start: 0.879, end: 1.0, downsample: 10"
