pointcloud_filter_node:
  ros__parameters:
    input_topic: "/points"
    output_topic: "/points/filtered"
    y_rotation_angle: 0.1570796 
    x_traslation: 0.
    y_traslation: 0.
    z_traslation: 1.
    gradient: true
    intensity: false
    angle_zones:  #OT128
      - "start: 0.000, end: 0.133, downsample: 5"
      - "start: 0.133, end: 0.465, downsample: 3"
      - "start: 0.465, end: 0.668, downsample: 1"
      - "start: 0.668, end: 0.820, downsample: 3"
      - "start: 0.820, end: 0.850, downsample: 7"
