pointcloud_filter_node:
  ros__parameters:
    input_topic: "/lidar/points"
    output_topic: "/lidar/filtered"
    y_rotation_angle: -0.1570796 
    x_traslation: 0.
    y_traslation: 0.
    z_traslation: 1.
    gradient: true
    intensity: false
    vertical_zones:
      - "start: 0.0, end: 0.1824375, downsample: 45"        # OT-128
      - "start: 0.1824375, end: 0.4704375, downsample: 10"
      - "start: 0.4704375, end: 0.6735625, downsample: 1"
      - "start: 0.6735625, end: 0.8175625, downsample: 20"
      - "start: 0.8175625, end: 1.0, downsample: 45"
      #- "start: 0.0, end: 0.1824375, downsample: 45"        # OT-128 reverse
      #- "start: 0.1824375, end: 0.3264375, downsample: 10"
      #- "start: 0.3264375, end: 0.5295625, downsample: 1"
      #- "start: 0.5295625, end: 0.8175625, downsample: 20"
      #- "start: 0.8175625, end: 1.0, downsample: 45"